// 保持为简短的服务器级提示；完整研究工作流由 Agent Skill 承担。
export const MCP_INSTRUCTIONS = [
  "# BitSearch MCP Server Usage Guide",
  "",
  "Use BitSearch for source-backed web research and retrieval through the currently exposed tools.",
  "",
  "## Tool routing",
  "- Use `web_search` for open-web discovery and `get_sources` when the cached source list is needed.",
  "- Use `web_fetch` for one known URL and `web_map` only for URL discovery.",
  "- Use `tavily_crawl` for synchronous single-site traversal when that tool is exposed.",
  "- Use `firecrawl_batch_scrape` for multiple known URLs and `firecrawl_extract` for structured fields or JSON.",
  "- Provider-native tools do not participate in generic routing; use the currently exposed tool descriptions.",
  "",
  "## Planning and results",
  "- Use the Planning Engine for ambiguous, multi-hop, or genuinely complex research tasks.",
  "- For a simple single-lookup question, use the shortest correct retrieval path.",
  "- When a result includes `result_id` and `next_cursor`, call `get_result_page` for more content.",
  "- After submitting an asynchronous Firecrawl job, poll its matching status tool until a terminal state when the final result is needed.",
  "",
  "Tool availability and provider routing can change with server configuration. These are usage hints, not authorization or security controls.",
].join("\n");
