export const MCP_INSTRUCTIONS = [
  "# BitSearch MCP Server Usage Guide",
  "",
  "## Planning Workflow (MANDATORY)",
  "",
  "For any research, investigation, or multi-step question, you MUST use the `plan_*` tool series BEFORE calling any search or fetch tool (`web_search`, `web_fetch`, `tavily_crawl`, etc.).",
  "",
  "The planning pipeline is:",
  "",
  "1. `plan_intent` - Analyze what the user is asking and identify ambiguities.",
  "2. `plan_complexity` - Assess complexity level (1-3) and estimate sub-queries/tool calls.",
  "3. `plan_sub_query` - Decompose into independent sub-queries (one call per sub-query).",
  "4. `plan_search_term` - For each sub-query, define search terms (one call per term).",
  "5. `plan_tool_mapping` - Map each sub-query to a specific search tool (web_search / tavily_crawl / web_fetch).",
  "6. `plan_execution` - Define execution order (parallel groups vs sequential).",
  "",
  "After ALL plan tools complete, execute the actual searches according to the plan.",
  "",
  "## When to skip planning",
  "- Simple factual questions with a single lookup → may go directly to `web_search`.",
  "- User explicitly says \"skip planning\" → skip.",
  "",
  "## Result Pagination",
  "- Large results return a `result_id`. Use `get_result_page` with `cursor`/`item_index` for more pages.",
].join("\n");
